name: production
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - black
    - flake8
    - isort
    - mypy
    - pip-tools
    - pip-compile
    - pre-commit
    - autopep8
    - scipy
    - numpy
    - pandas
    - scikit-learn
    - matplotlib
    - seaborn
    - tensorflow
    - requests
    - uvicorn
    - gunicorn
    - aiologger
    - python-dotenv
    - sqlparse
    - psycopg2-binary
    - dnspython
    - cryptography
    - pyjwt
    - pydantic
    - python-multipart
    - fastapi
    - connexion
    - python-jose
    - pyOpenSSL
    - PyNaCl
    - h5py
    - psutil
    - ldap3
    - idna
    - certifi
    - requests-toolbelt
    - toml
    - watchdog
    - gitpython
    - giturlparse
    - memory-profiler
    - redis
    - aioredis
    - motor
    - pymongo
    - aiomysql
    - mysqlclient
    - pyodbc
    - asyncpg
    - pynamodb
    - cassandra-driver
    - aiopg
    - psycopg2
    - sqlacodegen
    - alembic
    - ipython
    - ipykernel
    - tornado
    - tqdm
    - pytz
    - pyyaml
    - packaging
    - python-dateutil
    - python-iso8601
